Implement InterruptNumber for bare_metal::Nr
rust-embedded/cortex-m pull request #266
Opened 2020-09-20 13:56 UTC by adamgreig

This PR aims to help backwards compatibility by implementing the new `InterruptNumber` trait (coming in cortex-m 0.7) for the old `bare_metal::Nr` trait. With this included in cortex-m 0.7, existing PACs generated from the current svd2rust (0.17) will work with cortex-m 0.7, and new PACs generated from a to-be-released svd2rust which uses `InterruptNumber directly will also work.

We can then remove this implementation in cortex-m 0.8 and upgrade cortex-m to depend on bare-metal 1.0 (or not depend on it at all) at that time.

2020-09-20 13:56 UTC, rust-highfive commented
r? @therealprof

(rust_highfive has picked a reviewer for you, use r? to override)

2020-09-20 14:12 UTC, therealprof commented
I was kinda hoping we would march towards 1.0 rather sooner than later. 😅 

Other than that, looks fine to me. Other opions? @jonas-schievink @thalesfragoso

2020-09-21 06:12 UTC, thalesfragoso submitted a review, later dismissed
I agree with this change, thanks Adam.

2020-09-21 21:27 UTC, therealprof requested changes
I think this is worth mentioning in the CHANGELOG.

2020-09-21 23:44 UTC, therealprof commented on CHANGELOG.md
> +  which are `Nr + Copy`, but this will be removed in cortex-m v0.8.
Do we really want to tie this to a specific version already?

2020-09-21 23:55 UTC, therealprof approved these changes
LGTM, too. Thanks!

bors r+

2020-09-21 23:58 UTC, merged