Prepare for v0.7.0
rust-embedded/cortex-m pull request #286
Opened 2020-11-09 19:18 UTC by adamgreig

I think I got everything in the changelog updates but please point out anything I missed. Anything else missing before we're ready for 0.7.0?

Note that my plan is to now release cortex-m-semihosting 0.3.6 (with support for cortex-m >0.5&&<0.8) and 0.4.2 (cortex-m ^0.7, with our recent breaking changes) _after_ cortex-m 0.7 is out.

2020-11-09 19:18 UTC, rust-highfive commented
r? @jonas-schievink

(rust_highfive has picked a reviewer for you, use r? to override)

2020-11-09 19:19 UTC, adamgreig commented
NB closes https://github.com/rust-embedded/cortex-m/issues/281

2020-11-09 19:23 UTC, jonas-schievink commented
Don't think I currently have time to review this. r? @therealprof

2020-11-09 22:34 UTC, thalesfragoso requested changes
Thanks, regarding CI, it seems like we hit https://github.com/rust-lang/rust/issues/39935

2020-11-09 22:34 UTC, thalesfragoso commented on CHANGELOG.md
> +  non-brekaing changes
```suggestion
  non-breaking changes
```

2020-11-09 22:36 UTC, thalesfragoso commented
Oh, another thing, I thought we would incorporate `panic-itm` before releasing `0.7.0`, is this still the plan ?

2020-11-09 23:46 UTC, adamgreig commented on CHANGELOG.md
> +  non-brekaing changes
Thanks, force-pushed a fix.

2020-11-09 23:48 UTC, adamgreig commented
> Oh, another thing, I thought we would incorporate `panic-itm` before releasing `0.7.0`, is this still the plan ?

We can merge panic-itm into this repository after releasing 0.7, and then make a new release of panic-itm with updated links and a dependency allowing use with cortex-m 0.7 at the same time. Since the crates still get published separately (at least for now), there's no need to merge it before cortex-m 0.7 is released, as I understand it anyway.

2020-11-10 09:46 UTC, hug-dev commented
Are the items in the `src/peripheral/sau.rs` going to be released as well?

2020-11-10 18:56 UTC, adamgreig commented
> Are the items in the `src/peripheral/sau.rs` going to be released as well?

Yep, I missed those off the CHANGELOG updates somehow. Everything in the current master branch will be included. I'll update the changelog, thanks!

2020-11-10 21:42 UTC, therealprof approved these changes
LGTM, went through all the changes and I think it's complete.

bors r+

2020-11-10 21:43 UTC, therealprof commented
@thalesfragoso Happy? If so could you remove the change request?

2020-11-10 22:31 UTC, thalesfragoso approved these changes
Sorry for holding this, I thought my review would be dismissed by the new changes. Anyways, thanks again!

bors r+

2020-11-10 22:34 UTC, merged

2020-11-10 23:50 UTC, adamgreig commented
v0.7.0 is released :tada: