Small critical-section-related fixes.
rust-embedded/cortex-m pull request #451
Opened 2022-08-21 22:20 UTC by Dirbaio

See individual commit messages.

2022-08-21 23:23 UTC, adamgreig commented
While we're here, could you add the feature to the "Optional features" section of the docs in `src/lib.rs` please?

2022-08-22 12:58 UTC, Dirbaio commented
Done

2022-08-22 17:18 UTC, thejpster submitted a review, later dismissed
LGTM

2022-08-22 18:15 UTC, adamgreig requested changes
Few wording tweaks to highlight that even some single-core systems cannot use the feature, e.g. if unprivileged (see #233) or for things like softdevice or an RTOS.

2022-08-22 18:15 UTC, adamgreig commented on src/lib.rs
> +//! implementation suitable for single-core targets, based on disabling interrupt globally.
```suggestion
//! implementation suitable for single-core targets, based on disabling interrupts globally.
```

2022-08-22 18:15 UTC, adamgreig commented on src/lib.rs
> +//! implementation that synchronizes all cores instead, typically provided by the HAL crate.
```suggestion
//! It is **unsound** to enable it on multi-core targets or for code running in unprivileged mode,
//! and may cause functional problems in systems where some interrupts must be not be disabled
//! or critical sections are managed as part of an RTOS.
//! You should use a target-specific implementation instead, typically provided by a HAL crate.
```

2022-08-22 18:15 UTC, adamgreig commented on src/macros.rs
> +/// have to provide one from elsewhere, typically your chip's HAL crate.
```suggestion
/// This macro requires a `critical-section` implementation to be set. For most single core systems,
/// you can enable the `critical-section-single-core` feature for this crate. For other systems, you
/// have to provide one from elsewhere, typically your chip's HAL crate.
```

2022-08-22 18:31 UTC, adamgreig approved these changes
thanks!

bors r+

2022-09-04 02:09 UTC, adamgreig commented
bors retry

2022-09-04 02:17 UTC, merged